version: '3'

services:
  postgres:
    image: postgres:15.4
    volumes:
      - ../../postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ada-lovelace
      - POSTGRES_PASSWORD=cielo123
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=customer
    ports:
      - 5432:5432
    networks:
      - postgre-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - 3762:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: customer
      DB_USER: ada-lovelace
      DB_SCHEMA: public
      DB_PASSWORD: cielo123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ../others/keycloak
        target: /opt/keycloak/data/import
    networks:
      - postgre-network
    command: -v start-dev --import-realm
    depends_on:
      - postgres

networks:
  postgre-network:
    driver:
      bridge
